### ISSUE TITLE
I encountered a problem using rlooper

### ISSUE THREAD

**Issue by PEHGP** [chedinlab/rlooper#1]
Dear sir
I encountered an error using rlooper.

```
rlooper test.fasta test_out
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stol
Aborted (core dumped)
```
![捕获](https://user-images.githubusercontent.com/4146079/55051169-04a55400-508f-11e9-8589-363f632e6bbf.PNG)

What am I doing wrong?
Thanks very much!

**Comment by garden-of-delete** [comment]
Hi Kuan.

Could you send me your test.fasta file?

Best,
-- Robert

**Comment by PEHGP** [comment]
Hi Robert
The fasta as follows
Thank you very much!

```
>BN5-88_fwd_merge_peak_1
GTTTTTTTTTGTTTTTTTTTCTTTGCTCTGTTTTCTCGCTCCGGAAAAGTTTGAAGTTATATTTTATTAGTATGTAAAGAAGAGAAAAAGGGGGAAAGAAGAGAGAAGAAAAATGCAGAAAATCATATATATGAATTGGAAAAAAGTATATGTAATAATAATTAGTGCATCGTTTTGTGGTGTAGTTTATATAAATAAAGTGATATATAGTCTTGTATAAGAAAGGGATTTTACATGAGACCCAAATATGAGTAAAGGGTGTTGGCTCAAAGATTCATTTAGCAACCAAAGTTGCATTTGCAAGGAAATGAAAAGGTGTTAACAATGTCACTGCG
```
Best,
--Kuan

**Comment by PEHGP** [comment]
> Hi Robert
> The fasta as follows
> Thank you very much!
> 
> ```
> >BN5-88_fwd_merge_peak_1
> GTTTTTTTTTGTTTTTTTTTCTTTGCTCTGTTTTCTCGCTCCGGAAAAGTTTGAAGTTATATTTTATTAGTATGTAAAGAAGAGAAAAAGGGGGAAAGAAGAGAGAAGAAAAATGCAGAAAATCATATATATGAATTGGAAAAAAGTATATGTAATAATAATTAGTGCATCGTTTTGTGGTGTAGTTTATATAAATAAAGTGATATATAGTCTTGTATAAGAAAGGGATTTTACATGAGACCCAAATATGAGTAAAGGGTGTTGGCTCAAAGATTCATTTAGCAACCAAAGTTGCATTTGCAAGGAAATGAAAAGGTGTTAACAATGTCACTGCG
> ```
> Best,
> --Kuan


I already know.
The fasta header wrong!
Thank you very much!

**Comment by garden-of-delete** [comment]
Looks like that is the problem. Be sure to take a look at the full manual for useful guidance on how to use the different options, and how to interpret the output. 

Glad I could help. I am working on making the header parser more flexible in future releases.
