### ISSUE TITLE
How to enumerate R-loop states, calculates their energies from Eq. 1

### ISSUE THREAD

**Issue by PEHGP** [chedinlab/rlooper#3]
Hi Robert

Thank you for your help.
I have a question about your paper.
How to enumerate R-loop states, calculates their energies from Eq. 1?

Thank you very much!
Best,
-- kuan

**Comment by garden-of-delete** [comment]
Take a look at the `--dump` option. It will output all of the R-loop states and their energies to a file for further analysis. I have to double check, but I believe it also outputs the energy of the ground state (no R-loop) as either the first or the last entry.

**Comment by PEHGP** [comment]
Thank you very much!
I may not have described the problem clearly.
I don't understand the algorithm for enumerating R-loop states.
Do you split the windows on the sequence first,and then calculate the energy in each bin ?

**Comment by garden-of-delete** [comment]
The widower object partitions the input sequence into all possible sub-sequences, passing iterators to the start and end locations of each sub-sequence to a set of functions that ultimately computes the energies. The code is object oriented, but not particularly simple. I can answer any specific questions you have, but you might just have to stare at it / step through it to understand how it works.
