### ISSUE TITLE
How to analyze non-template strand

### ISSUE THREAD

**Issue by mmferrari** [chedinlab/rlooper#6]
Hi,
I am interested in using R-looper for analyzing the R-loop formation between the sense (non-template) strand and the antisense RNA (i.e. the RNA complementary to the sense strand).
My FASTA file contains the antisense (template) sequence (in the 5'-3' direction).

Right now I am using the following command to analyze the non-template strand: `rlooper antisense_strand.fa output --N auto --dump --localaverageenergy --invert`; is it correct?

About the base pair locations in the dump file, do they correspond to the input sequence (in this case, template sequence)?

Thanks.

**Comment by garden-of-delete** [comment]
Orientation can be tricky. While I can't be 100% sure with the information you have given, I believe the use of --invert is not proper here. 

- R-looper internally considers base pairs in the order they would interact with the polymerase. If the strand in the fasta header is specified as '+' (indicating the provided sequence is the sense sequence 5'->3'), then the sequence is automatically complemented (so as to consider the template strand in the 3'->5' direction). 
- Similarly, if the fasta header is specified as '-' (indicating the complement of the provided sequence is the sense sequence), then the provided sequence is automatically reversed. 

In your situation, you are providing what you are calling the antisense sequence in the reverse order from what the polymerase would encounter. Therefore, you could get proper treatment of this sequence by specifying the strand as '-' (so as to reverse the provided sequence) without the use of any other sequence commands (--invert, --reverse, or --complement). 

The simplest thing to do in the case of arbitrary sequence is provide the sense sequence to R-looper (in 5'->3' orientation), and indicate that to be the case by using '+' in the fasta header.

**Comment by mmferrari** [comment]
Hi,
I think my question was not clear. I will try to clarify with an example.
Let's say I have a gene where:
sense (non-template) strand: 5'-ATG...CCA-3'
antisense (template) strand: 5'-TGG...CAT-3'

I want to analyze the R-loops formed during transcription of the sense strand.
From your previous explanation, I can do that by specifying the sequence TGG...CAT (5'->3') as '+' OR the sequence ATG...CCA (5'->3') as '-' in the FASTA header. Is it correct?

About the dump file, let us assume that in one row I have: start_position=2 and stop_position=20. Do these locations represent the 2nd and 20th nucloetide in the input sequence (5'->3') specified in the FASTA header?
I assume the same base pair ordering is used as x-axis in all the other output files (e.g. .wig).

**Comment by mmferrari** [comment]
Any news about this?

**Comment by garden-of-delete** [comment]
I updated the README to clarify the language around the input sequence. For simplicity, the input sequence should always be provided in 5' to 3' orientation (though the --reverse option can be used if the sequence is known to be in the 3' to 5' orientation). Independently, the non-template strand (sense strand) should be specified in the fasta header as described in the readme. 

Also, yes, the coordinates in the dump file should now correctly match the coordinates of the input sequence. 

Thanks for bringing these issues to my attention.

**Comment by garden-of-delete** [comment]
> Orientation can be tricky. While I can't be 100% sure with the information you have given, I believe the use of --invert is not proper here.
> 
> * R-looper internally considers base pairs in the order they would interact with the polymerase. If the strand in the fasta header is specified as '+' (indicating the provided sequence is the sense sequence 5'->3'), then the sequence is automatically complemented (so as to consider the template strand in the 3'->5' direction).
> * Similarly, if the fasta header is specified as '-' (indicating the complement of the provided sequence is the sense sequence), then the provided sequence is automatically reversed.
> 
> In your situation, you are providing what you are calling the antisense sequence in the reverse order from what the polymerase would encounter. Therefore, you could get proper treatment of this sequence by specifying the strand as '-' (so as to reverse the provided sequence) without the use of any other sequence commands (--invert, --reverse, or --complement).
> 
> The simplest thing to do in the case of arbitrary sequence is provide the sense sequence to R-looper (in 5'->3' orientation), and indicate that to be the case by using '+' in the fasta header.

I want to add that my language in this response was unclear, and probably produced some confusion. The use of '+' does not specify which strand is in the 5' to 3' orientation. It specifies the non-template strand.
