### ISSUE TITLE
Unconstrained parameter

### ISSUE THREAD

**Issue by mmferrari** [chedinlab/rlooper#7]
Hi,

Could you clarify the relationship between the option `--unconstrained` and the parameter `--N`? It seems to me that when `--unconstrained` is specified, then the software does not take into account `--N`. Is that correct?

Thanks.

**Comment by garden-of-delete** [comment]
Sure. `--unconstrained` treats the molecule as topologically unconstrained. In the model, this eliminates the superhelicity term, which includes N. With `--unconstrained` on, the energies of different possible R-loop structures boil down to base pairing energetics and the junctional energy. 

In contrast, specifying `--sigma 0.00` best models a topologically constrained but relaxed molecule. In this case, overtwist produced by the strand separation in the R-loop structure is unfavorable, and should be factored into the energy of the R-loops. 

Hope that helps.
