### ISSUE TITLE
Rlooper performance on long sequences

### ISSUE THREAD

**Issue by sutormin94** [chedinlab/rlooper#9]
Dear Robert,

Do you have any estimations on the algorithm performance? For example, is it worth doing a whole bacterial genome scanning (4.6*10^6 bp)? I made an attempt on a 3.00GHz core and after 24h it is still running. 

Best,
Dmitry S

**Comment by garden-of-delete** [comment]
Hi Dimitry.

The algorithm's performance is not good on very large sequences. R-looper
computes the full biophysical ensemble, with a number of r-loop structures
scaling like approximately n! with sequence length n.

I have considered some straightforward changes towards an approximation of
the full ensemble, which would allow much larger sequences to be run, but I
decided against it for these reasons:
- Superhelicity is an input for the model, and is assumed to be constant
across the entire superhelical domain. This assumption means that the
handling of superhelicity by the model gets farther and farther away from
reality over large sequences.
- The model assumes that a complementary RNA molecule is present to take
place in an equilibrium energetic competition over the entire provided
sequence. This is obviously not the case to the extreme on the scale of an
entire genome.

I would recommend choosing specific, gene-scale sequences of interest, and
restricting the input sequence to those regions. In a prokaryotic genome is
is probably appropriate to use `--sigma -0.07` and `--N auto` for this
application.

Best,
-- Robert

**Comment by sutormin94** [comment]
Thanks, Robert!
